### ISSUE TITLE
record-edit-form does not work inside the modal

### ISSUE THREAD

**Issue by Damecek** [jamessimone/lwc-modal#1]
Embeding ligthning-record-edit-form inside the modal shows weird behavior. 
- all fields are set as errors
- the 'required' validation is not working

![image](https://user-images.githubusercontent.com/46635736/112332703-4129db80-8cba-11eb-86e1-b08b401e9dac.png)

```html
<c-modal modal-header="Create New Claim"
             modal-save-handler={firstModalSaveHandler}
             modal-button-text="Save"
             data-id="first-modal">
        <div slot="modalContent" class="modalContent slds-modal__content slds-p-around_medium">
            <lightning-record-edit-form object-api-name="ImpartnerMDF__FundsClaim__c" onsuccess={handleSuccess}>
                <lightning-messages></lightning-messages>
                <lightning-input-field field-name="ImpartnerMDF__FundsRequest__c" value={recordId} disabled></lightning-input-field>
                <lightning-input-field field-name="ImpartnerMDF__PaymentAmount__c" required></lightning-input-field>
                <lightning-input-field field-name="ImpartnerMDF__InvoiceNumber__c" required></lightning-input-field>
                <lightning-input-field field-name="Invoice_Payee_Name__c" required></lightning-input-field>
                <lightning-input-field field-name="Invoice_Date__c" required></lightning-input-field>
            </lightning-record-edit-form>
        </div>
    </c-modal>
```

```javascript
 firstModalSaveHandler = (event) => {
        this.template.querySelector('lightning-record-edit-form').submit();
    }

    lastClaimId;

    handleSuccess(event) {
        const file = this.template.querySelector('lightning-file-upload');
        file.recordId = event.detail.id;
        this.lastClaimId = event.detail.id;

        this.template.querySelector('[data-id="first-modal"]').toggleModal();
        this.template.querySelector('[data-id="second-modal"]').toggleModal();
    }
```

**Comment by jamessimone** [comment]
@Damecek interesting, I believe I know what the issue is. I may not have the chance to investigate till later in the week but I will keep you updated - thanks for reporting this!

**Comment by jamessimone** [comment]
@Damecek I wasn't able to get to this issue this weekend but it is now my top-most priority. Apologies for the delay - I will keep you updated.

**Comment by Damecek** [comment]
@jamessimone I implemented workaround with toast message so no need to hurry. I managed to locate the issue into the focusFirstChild function, if I comment it out all looks to be working as expected.

**Comment by jamessimone** [comment]
@Damecek yup, that’s what I expected. It “breaks” one of the accessibility pieces of the modal: it’s expected that when a modal opens, the first focusable element is selected, but I’m glad you’ve found a workaround for now

**Comment by jamessimone** [comment]
@Damecek you can get the updated version now - I don't intend for the current fix to be there long-term, but I need to follow up with the LWC team on the exact issue that you were experiencing now that I've looked into it a bit more. In any case, thanks for reporting this!
