### ISSUE TITLE
doesnt seem to work anymore

### ISSUE THREAD

**Issue by sjurgis** [jamessimone/lwc-modal#4]
This is what I see with spring 22
<img width="563" alt="Screen Shot 2022-03-10 at 2 47 31 PM" src="https://user-images.githubusercontent.com/7092409/157571494-77d7732e-9d0a-4252-ab50-346d717108ee.png">

**Comment by jamessimone** [comment]
Interesting. I will take a look at this in the coming days! Thanks for reporting.

**Comment by jamessimone** [comment]
@sjurgis I was unable to reproduce:

![image](https://user-images.githubusercontent.com/16430727/157673696-1027a7dc-6c22-4f0a-afe8-8adf8c47df07.png)

I would put lightning debug mode on and see if there are other errors on your page that are preventing the modal from working.

**Comment by sjurgis** [comment]
Hi thanks for checking. Maybe I misunderstand idioms of how this should be consumed.
Anyway used this one and worked well - https://github.com/Prashanth-1923/Reusable-Modal-Component-in-LWC

**Comment by jamessimone** [comment]
@sjurgis I’m happy to walk through anything I can with you — slot-based composition should be fairly easy. The modal you’ve linked to (in addition to seemingly have copied + pasted the names I’ve used here) is much less accessible/thorough.
