### ISSUE TITLE
Shift + Tab - breaks trapped focus

### ISSUE THREAD

**Issue by AlexandraGrassi** [jamessimone/lwc-modal#5]
When I press Shift + Tab, the focus is moved outside the modal

**Comment by jamessimone** [comment]
Thanks for submitting. I’ll have to have a look.

**Comment by jamessimone** [comment]
@AlexandraGrassi just pushed some updates for this - they should address the issue for you. Thanks again for reporting!

**Comment by AlexandraGrassi** [comment]
Thank you for such a great component! It was really an issue for me to create an accessible one.
